schema: "classroom50/repo-config/v1"
classroom: "dmg1"
assignment: "lab5-test"
owner:
  username: "firdawse21"
  id: 159532273
  accepted_at: "2026-08-18T17:58:20Z"
source:
  owner: "UM6P-CC"
  owner_id: 231446913
  repo: "um6p-cc-databases-26-lab-0-DM1-1"
  branch: "main"
